name: syzygy
description: Syzygy Flame game
version: 0.0.0
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ^3.13.0
flutter:
  assets:
    - assets/images/

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.19.0